set(interbotix_joy_control_MESSAGE_FILES "/home/anusha2631/CS5335_Final_Project/interbotix_ws/src/interbotix_ros_arms/interbotix_examples/interbotix_joy_control/msg/ArmJoyControl.msg")
set(interbotix_joy_control_SERVICE_FILES "")
